// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiijtccbbkanvrzknzpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppaWp0Y2NiYmthbnZyemtuenBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODg4MTcsImV4cCI6MjA3NDQ2NDgxN30.qBsSJAYn9l9sBEp9hsJ996n7gZ4yFldXFgmLqteybYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});